version: '3'
services:
  nginx:
    image: nginx:1.12
    container_name: sand-nginx
    ports:
      - 8081:80
    volumes:
      - ./:/sandbox/
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  app:
    container_name: sand-app
    build: ./docker/app
    volumes:
      - ./:/sandbox/
      - ./docker/app/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - db

  composer:
    container_name: sand-composer
    build: ./docker/composer
    volumes:
      - ./:/sandbox/
    working_dir: /sandbox/

  node:
    image: node:lts
    container_name: sand-node
    volumes:
      - .:/sandbox/
    working_dir: /sandbox/
    entrypoint: ["npm"]
    command: ["help"]

  db:
    image: postgres:12.3
    container_name: sand-db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'sandbox'
    volumes:
      - sandbox-db:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  sandbox-db:
    driver: local
